### ISSUE TITLE
[Frontend] Cache dependencies in workflows

### ISSUE THREAD

**Issue by weronikaolejniczak** [weronikaolejniczak/chEAT-frontend#20]
**To do:**

- [x] Add step before installing dependencies.
```yaml 
  - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
```
- [x] Update install dependencies steps to run [if there's no cache](https://github.com/actions/cache)
